# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: shoulder
channels:
- conda-forge
dependencies:
- biorbd
- bioviz
- python
- numpy
- scipy
- matplotlib
- mujoco-python
- mediapy
- ffmpeg-python
- pyyaml
- imageio
- casadi
- ipopt
- plyfile
- numpy-stl
- pip:
  - myosuite
  - circle-fitting-3d